In [3]:
#imports
import numpy as np
import pandas as pd
import os
for dirname, _, filenames in os.walk('input'):
    for filename in filenames:
        print(os.path.join(dirname,filename))

input\Fake.csv
input\True.csv

In [4]:
truenews = pd.read_csv('True.csv')
fakenews = pd.read_csv('Fake.csv')

In [5]:
fakenews.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [6]:
truenews.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [7]:
fakenews.describe()
#truenews.describe()

,title,text,subject,date
count,23481,23481,23481,23481
unique,17903,17455,6,1681
top,MEDIA IGNORES Time That Bill Clinton FIRED His...,,News,"May 10, 2017"
freq,6,626,9050,46

In [8]:
truenews['T/F'] = 'True'
fakenews['T/F'] = 'Fake'
#Combining
news = pd.concat([truenews, fakenews])
news["Article"] = news["title"] + news["text"]
news.sample(frac = 1) #shuffle 100% of concat
# #Cleaning
# from nltk.corpus import stopwords
# import string
# def process_text(s):
#     #removes punctuation from strings and joins adjacent strings tgt
#     nopunc = [char for char in s if char not in string.punctuation]
#     nopunc = ''.join(nopunc)
#     #lowercase all strings
#     clean_string = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
#     return clean_string

# news['Clean Text'] = news['Article'].apply(process_text)
# news.sample(5)

,title,text,subject,date,T/F,Article
19015,U.N. experts urge Aung San Suu Kyi to meet per...,GENEVA (Reuters) - Myanmar s leader Aung San S...,worldnews,"September 26, 2017",True,U.N. experts urge Aung San Suu Kyi to meet per...
5486,Collapse: ISIS Now Admits Obama’s Strategy Is...,"The Islamic State terrorist group, also known ...",News,"July 13, 2016",Fake,Collapse: ISIS Now Admits Obama’s Strategy Is...
12971,EU exec proposes deeper euro zone integration ...,BRUSSELS (Reuters) - The European Commission p...,worldnews,"December 5, 2017",True,EU exec proposes deeper euro zone integration ...
11672,FLASHBACK: CHICAGO RESIDENT Blasts Chicago May...,,politics,"Feb 13, 2017",Fake,FLASHBACK: CHICAGO RESIDENT Blasts Chicago May...
1350,"Democratic Senator Feinstein, 84, 'all in' on ...",WASHINGTON (Reuters) - Democrat Dianne Feinste...,politicsNews,"October 9, 2017",True,"Democratic Senator Feinstein, 84, 'all in' on ..."
...,...,...,...,...,...,...
12474,UNDERCOVER JOURNALIST In Burka Is Offered Huma...,,politics,"Nov 7, 2016",Fake,UNDERCOVER JOURNALIST In Burka Is Offered Huma...
216,U.S. Treasury tax study slammed as 'fake math'...,WASHINGTON (Reuters) - The U.S. Treasury Depar...,politicsNews,"December 11, 2017",True,U.S. Treasury tax study slammed as 'fake math'...
16499,U.N. nuclear chief to visit Iran this weekend,VIENNA (Reuters) - The head of the United Nati...,worldnews,"October 25, 2017",True,U.N. nuclear chief to visit Iran this weekendV...
101,BUSTED: Leaked Documents Prove Trump Took Lau...,Convincing President Trump to release his tax ...,News,"November 13, 2017",Fake,BUSTED: Leaked Documents Prove Trump Took Lau...
8965,"Advocates hail U.S. court abortion decision, p...",NEW YORK (Thomson Reuters Foundation) - Aborti...,politicsNews,"June 27, 2016",True,"Advocates hail U.S. court abortion decision, p..."

In [9]:
#Data Cleaning
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
import string
def process_text(s):

    # Check string to see if they are a punctuation
    nopunc = [char for char in s if char not in string.punctuation]

    # Join the characters again to form the string.
    nopunc = ''.join(nopunc)
    
    # Convert string to lowercase and remove stopwords
    clean_string = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
    return clean_string

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Albert\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [10]:
print(news['Article'])

0        As U.S. budget fight looms, Republicans flip t...
1        U.S. military to accept transgender recruits o...
2        Senior U.S. Republican senator: 'Let Mr. Muell...
3        FBI Russia probe helped by Australian diplomat...
4        Trump wants Postal Service to charge 'much mor...
                               ...
23476    McPain: John McCain Furious That Iran Treated ...
23477    JUSTICE? Yahoo Settles E-mail Privacy Class-ac...
23478    Sunnistan: US and Allied ‘Safe Zone’ Plan to T...
23479    How to Blow $700 Million: Al Jazeera America F...
23480    10 U.S. Navy Sailors Held by Iranian Military ...
Name: Article, Length: 44898, dtype: object

In [11]:
news['Clean Text'] = news['Article'].apply(process_text)

In [12]:
news.sample(5)

,title,text,subject,date,T/F,Article,Clean Text
13963,POLL: Who Should Donald Trump Choose For Vice ...,,politics,"May 7, 2016",Fake,POLL: Who Should Donald Trump Choose For Vice ...,"[POLL, Donald, Trump, Choose, Vice, President]"
15991,"Britain accelerates Brexit plans, divorce talk...",LONDON/BRATISLAVA (Reuters) - Britain is accel...,worldnews,"October 31, 2017",True,"Britain accelerates Brexit plans, divorce talk...","[Britain, accelerates, Brexit, plans, divorce,..."
3114,"Mark Hamill Reads Trump Tweets As The Joker, ...",Donald Trump has been described by many as sou...,News,"January 7, 2017",Fake,"Mark Hamill Reads Trump Tweets As The Joker, ...","[Mark, Hamill, Reads, Trump, Tweets, Joker, It..."
1981,Sean Spicer Just Said Something About Trumpca...,"When Donald Trump fails, his team sure doesn t...",News,"March 27, 2017",Fake,Sean Spicer Just Said Something About Trumpca...,"[Sean, Spicer, Said, Something, Trumpcare, Mak..."
11699,EU executive moves to punish Poland over court...,BRUSSELS (Reuters) - The EU executive launched...,worldnews,"December 20, 2017",True,EU executive moves to punish Poland over court...,"[EU, executive, moves, punish, Poland, court, ..."

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
bow_transformer = CountVectorizer(analyzer = process_text).fit(news['Clean Text'])
#print(len(bow_transformer.vocabulary_))
news_bow = bow_transformer.transform(news['Clean Text'])
#print('Shape of Sparse Matrix: ', news_bow.shape)
#print('Amount of Non-Zero occurences: ', news_bow.nnz)
sparsity = (100.0 * news_bow.nnz / (news_bow.shape[0] * news_bow.shape[1]))
print('sparsity: {}'.format(round(sparsity)))

sparsity: 0

In [14]:
from sklearn.feature_extraction.text import TfidfTransformer

tfidf_transformer = TfidfTransformer().fit(news_bow)
news_tfidf = tfidf_transformer.transform(news_bow)
print(news_tfidf.shape)

(44898, 39099)

In [18]:
from sklearn.naive_bayes import MultinomialNB
fakenews_detect_model = MultinomialNB().fit(news_tfidf, news['T/F'])

In [19]:
#Model Evaluation
predictions = fakenews_detect_model.predict(news_tfidf)
print(predictions)

['True' 'True' 'True' ... 'Fake' 'Fake' 'Fake']

In [21]:
from sklearn.metrics import classification_report
print (classification_report(news['T/F'], predictions))

              precision    recall  f1-score   support

        Fake       1.00      1.00      1.00     23481
        True       1.00      1.00      1.00     21417

    accuracy                           1.00     44898
   macro avg       1.00      1.00      1.00     44898
weighted avg       1.00      1.00      1.00     44898

In [23]:
from sklearn.model_selection import train_test_split

news_train, news_test, text_train, text_test = train_test_split(news['Article'], news['T/F'], test_size=0.3)

print(len(news_train), len(news_test), len(news_train) + len(news_test))

31428 13470 44898

In [ ]:
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ('bow', CountVectorizer(analyzer=process_text)),  
    ('tfidf', TfidfTransformer()),  
    ('classifier', MultinomialNB()),  
])
pipeline.fit(news_train,text_train)

prediction = pipeline.predict(news_test)

print(classification_report(prediction,text_test))